package br.com.keli.keli_backend.model;

public enum TipoMaterial {
    DESINFETANTE, ALCOOL, BACTERICIDA, AGUA_SANITARIA, SABÃO, DESENGORDURANTE, LIMPADOR_MULTIUSO, LIMPADOR_ELETRÔNICO, LIMPADOR_MOVEL, LIMPADOR_ESTOFADO, LIMPADOR_PISO, LIMPADOR_CARPETE, LIMPADOR_VIDRO, LIMPADOR_BANHEIRO, ANTI_MOFO, REMOVEDOR_MOFO, TIRA_MANCHA, ALVEJANTE, REMOVEDOR, DETERGENTE, AMACIANTE, AROMATIZANTE, NEUTRALIZADOR_ODOR, TOALHA_DESINFETANTE, LIMPADOR_NATURAL, DESENGRAXANTE, EPI, FERRAMENTA, PRODUTO_PET, PRODUTO_AUTOMOTIVO
}
